name: Anime Scraper
on:
  schedule:
    - cron: '0 * * * *' # Har ghante chalega
  workflow_dispatch: # Manual test ke liye button milega

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: {python-version: '3.9'}
      - name: Install dependencies
        run: pip install gspread oauth2client requests beautifulsoup4
      - name: Run Scraper
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
        run: python scraper.py
