name: Auto Scraper
on:
  schedule:
    - cron: '0 */6 * * *' # Har 6 ghante mein run hoga
  workflow_dispatch:      # Tu button daba kar bhi run kar sakega

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests gspread google-auth
      - name: Run Scraper
        run: python scraper.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
